name: chat_new
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  image_picker: ^0.8.6
  lottie: ^1.3.0

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Calisto
      fonts:
        - asset: fonts/calistomt.ttf
