// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAW0nIad6engx7m38kEkl9SEwWxOrLaWU',
    appId: '1:437365214494:web:8e48dd81bc18be77edcd0f',
    messagingSenderId: '437365214494',
    projectId: 'grasaasmobil',
    authDomain: 'grasaasmobil.firebaseapp.com',
    storageBucket: 'grasaasmobil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYNZTrTIEeRnyLe5L5UUIJA70O-pScbwo',
    appId: '1:437365214494:android:f8029613a95ff76cedcd0f',
    messagingSenderId: '437365214494',
    projectId: 'grasaasmobil',
    storageBucket: 'grasaasmobil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJ5Sw4gtUHug3LRVgsK7HbhVC0dTdTOo',
    appId: '1:437365214494:ios:fd05dcd1e32bbaacedcd0f',
    messagingSenderId: '437365214494',
    projectId: 'grasaasmobil',
    storageBucket: 'grasaasmobil.appspot.com',
    iosClientId: '437365214494-ru69a4r41ndcnp3krtfl0hq55pg06bs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJ5Sw4gtUHug3LRVgsK7HbhVC0dTdTOo',
    appId: '1:437365214494:ios:fd05dcd1e32bbaacedcd0f',
    messagingSenderId: '437365214494',
    projectId: 'grasaasmobil',
    storageBucket: 'grasaasmobil.appspot.com',
    iosClientId: '437365214494-ru69a4r41ndcnp3krtfl0hq55pg06bs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatNew',
  );
}
